services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - network

  app:
    image: project1-gateway:latest
    restart: unless-stopped
    working_dir: /var/www/sunrise/gateway
    volumes:
      - - /var/www/html/sunset/gateway:/var/www/sunrise/gateway
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis
    ports:
      - "9000:9000"
    networks:
      - network
      - grpc_network


  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - network
      - shared_net

  # apache:
  #   image: httpd:2.4
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - .:/var/www/sunrise/gateway
  #     - ./apache-config/httpd.conf:/usr/local/apache2/conf/httpd.conf
  #   depends_on:
  #     - app
  #   networks:
  #     - network

volumes:
  dbdata:

networks:
  network:
  shared_net:
    name: shared_net
    driver: bridge
  grpc_network:
    name: grpc_network
    driver: bridge
