<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums/getUsers.proto

namespace grpc\getUsers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>getUsers.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 user_details_id = 1;</code>
     */
    protected $user_details_id = 0;
    /**
     * Generated from protobuf field <code>string user_details_first_name = 2;</code>
     */
    protected $user_details_first_name = '';
    /**
     * Generated from protobuf field <code>string user_details_middle_name = 3;</code>
     */
    protected $user_details_middle_name = '';
    /**
     * Generated from protobuf field <code>string user_details_last_name = 4;</code>
     */
    protected $user_details_last_name = '';
    /**
     * Generated from protobuf field <code>string user_details_email = 5;</code>
     */
    protected $user_details_email = '';
    /**
     * Generated from protobuf field <code>string user_details_phone = 6;</code>
     */
    protected $user_details_phone = '';
    /**
     * Generated from protobuf field <code>string user_details_department = 7;</code>
     */
    protected $user_details_department = '';
    /**
     * Generated from protobuf field <code>string user_details_address = 8;</code>
     */
    protected $user_details_address = '';
    /**
     * Generated from protobuf field <code>string user_details_date_of_birth = 9;</code>
     */
    protected $user_details_date_of_birth = '';
    /**
     * Generated from protobuf field <code>string user_details_gender = 10;</code>
     */
    protected $user_details_gender = '';
    /**
     * Generated from protobuf field <code>string user_details_profile_image_URL = 11;</code>
     */
    protected $user_details_profile_image_URL = '';
    /**
     * Generated from protobuf field <code>string user_details_profile_image_name = 12;</code>
     */
    protected $user_details_profile_image_name = '';
    /**
     * Generated from protobuf field <code>string user_details_created_at = 13;</code>
     */
    protected $user_details_created_at = '';
    /**
     * Generated from protobuf field <code>string user_details_created_by_username = 16;</code>
     */
    protected $user_details_created_by_username = '';
    /**
     * Generated from protobuf field <code>string user_details_created_by_user_type = 17;</code>
     */
    protected $user_details_created_by_user_type = '';
    /**
     * Generated from protobuf field <code>string user_details_updated_at = 18;</code>
     */
    protected $user_details_updated_at = '';
    /**
     * Generated from protobuf field <code>string user_details_updated_by_username = 21;</code>
     */
    protected $user_details_updated_by_username = '';
    /**
     * Generated from protobuf field <code>string user_details_updated_by_user_type = 22;</code>
     */
    protected $user_details_updated_by_user_type = '';
    /**
     * Generated from protobuf field <code>string user_roles_type_1 = 26;</code>
     */
    protected $user_roles_type_1 = '';
    /**
     * Generated from protobuf field <code>string user_departments_department_name = 56;</code>
     */
    protected $user_departments_department_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_details_id
     *     @type string $user_details_first_name
     *     @type string $user_details_middle_name
     *     @type string $user_details_last_name
     *     @type string $user_details_email
     *     @type string $user_details_phone
     *     @type string $user_details_department
     *     @type string $user_details_address
     *     @type string $user_details_date_of_birth
     *     @type string $user_details_gender
     *     @type string $user_details_profile_image_URL
     *     @type string $user_details_profile_image_name
     *     @type string $user_details_created_at
     *     @type string $user_details_created_by_username
     *     @type string $user_details_created_by_user_type
     *     @type string $user_details_updated_at
     *     @type string $user_details_updated_by_username
     *     @type string $user_details_updated_by_user_type
     *     @type string $user_roles_type_1
     *     @type string $user_departments_department_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ums\GetUsers::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 user_details_id = 1;</code>
     * @return int|string
     */
    public function getUserDetailsId()
    {
        return $this->user_details_id;
    }

    /**
     * Generated from protobuf field <code>uint64 user_details_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserDetailsId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_details_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_first_name = 2;</code>
     * @return string
     */
    public function getUserDetailsFirstName()
    {
        return $this->user_details_first_name;
    }

    /**
     * Generated from protobuf field <code>string user_details_first_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_first_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_middle_name = 3;</code>
     * @return string
     */
    public function getUserDetailsMiddleName()
    {
        return $this->user_details_middle_name;
    }

    /**
     * Generated from protobuf field <code>string user_details_middle_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsMiddleName($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_middle_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_last_name = 4;</code>
     * @return string
     */
    public function getUserDetailsLastName()
    {
        return $this->user_details_last_name;
    }

    /**
     * Generated from protobuf field <code>string user_details_last_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_last_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_email = 5;</code>
     * @return string
     */
    public function getUserDetailsEmail()
    {
        return $this->user_details_email;
    }

    /**
     * Generated from protobuf field <code>string user_details_email = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_phone = 6;</code>
     * @return string
     */
    public function getUserDetailsPhone()
    {
        return $this->user_details_phone;
    }

    /**
     * Generated from protobuf field <code>string user_details_phone = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_department = 7;</code>
     * @return string
     */
    public function getUserDetailsDepartment()
    {
        return $this->user_details_department;
    }

    /**
     * Generated from protobuf field <code>string user_details_department = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsDepartment($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_department = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_address = 8;</code>
     * @return string
     */
    public function getUserDetailsAddress()
    {
        return $this->user_details_address;
    }

    /**
     * Generated from protobuf field <code>string user_details_address = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_date_of_birth = 9;</code>
     * @return string
     */
    public function getUserDetailsDateOfBirth()
    {
        return $this->user_details_date_of_birth;
    }

    /**
     * Generated from protobuf field <code>string user_details_date_of_birth = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsDateOfBirth($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_date_of_birth = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_gender = 10;</code>
     * @return string
     */
    public function getUserDetailsGender()
    {
        return $this->user_details_gender;
    }

    /**
     * Generated from protobuf field <code>string user_details_gender = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsGender($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_gender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_profile_image_URL = 11;</code>
     * @return string
     */
    public function getUserDetailsProfileImageURL()
    {
        return $this->user_details_profile_image_URL;
    }

    /**
     * Generated from protobuf field <code>string user_details_profile_image_URL = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsProfileImageURL($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_profile_image_URL = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_profile_image_name = 12;</code>
     * @return string
     */
    public function getUserDetailsProfileImageName()
    {
        return $this->user_details_profile_image_name;
    }

    /**
     * Generated from protobuf field <code>string user_details_profile_image_name = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsProfileImageName($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_profile_image_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_created_at = 13;</code>
     * @return string
     */
    public function getUserDetailsCreatedAt()
    {
        return $this->user_details_created_at;
    }

    /**
     * Generated from protobuf field <code>string user_details_created_at = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_created_by_username = 16;</code>
     * @return string
     */
    public function getUserDetailsCreatedByUsername()
    {
        return $this->user_details_created_by_username;
    }

    /**
     * Generated from protobuf field <code>string user_details_created_by_username = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsCreatedByUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_created_by_username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_created_by_user_type = 17;</code>
     * @return string
     */
    public function getUserDetailsCreatedByUserType()
    {
        return $this->user_details_created_by_user_type;
    }

    /**
     * Generated from protobuf field <code>string user_details_created_by_user_type = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsCreatedByUserType($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_created_by_user_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_updated_at = 18;</code>
     * @return string
     */
    public function getUserDetailsUpdatedAt()
    {
        return $this->user_details_updated_at;
    }

    /**
     * Generated from protobuf field <code>string user_details_updated_at = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_updated_by_username = 21;</code>
     * @return string
     */
    public function getUserDetailsUpdatedByUsername()
    {
        return $this->user_details_updated_by_username;
    }

    /**
     * Generated from protobuf field <code>string user_details_updated_by_username = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsUpdatedByUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_updated_by_username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_details_updated_by_user_type = 22;</code>
     * @return string
     */
    public function getUserDetailsUpdatedByUserType()
    {
        return $this->user_details_updated_by_user_type;
    }

    /**
     * Generated from protobuf field <code>string user_details_updated_by_user_type = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDetailsUpdatedByUserType($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_details_updated_by_user_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_roles_type_1 = 26;</code>
     * @return string
     */
    public function getUserRolesType1()
    {
        return $this->user_roles_type_1;
    }

    /**
     * Generated from protobuf field <code>string user_roles_type_1 = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setUserRolesType1($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_roles_type_1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_departments_department_name = 56;</code>
     * @return string
     */
    public function getUserDepartmentsDepartmentName()
    {
        return $this->user_departments_department_name;
    }

    /**
     * Generated from protobuf field <code>string user_departments_department_name = 56;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDepartmentsDepartmentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_departments_department_name = $var;

        return $this;
    }

}

